compute_environment: LOCAL_MACHINE
distributed_type: DEEPSPEED
deepspeed_config:
  gradient_accumulation_steps: 8
  gradient_clipping: 1.0
  offload_optimizer_device: none
  offload_param_device: none
  zero3_init_flag: true
  zero_stage: 3
  train_batch_size: 128
  train_micro_batch_size_per_gpu: 2

main_training_function: main
mixed_precision: bf16
downcast_bf16: 'no'

num_machines: 1
num_processes: 8
rdzv_backend: static
same_network: true
use_cpu: false